### ISSUE TITLE
Enable colored output for the Log window

### ISSUE THREAD

**Issue by cklb** [cklb/pymoskito#63]
Printing caught exceptions in color would make it easier to notice if something went wrong.

**Comment by TanDro** [comment]
Maybe a solution for you
https://github.com/umit-iace/pymoskito/commit/b01392996e9f4cbb311394f93bda63615a5983cb

**Comment by cklb** [comment]
This is great. I moved to color definitions into the system configuration file, since no one ever likes the default colors, see the `colored_log_branch`

**Comment by TanDro** [comment]
Yeah nice idea!
The settings solution can perhaps used for the plot colors. What do you mean?

**Comment by cklb** [comment]
I would rather provide a setting the specify the colormap (from matplotlib) to use.

**Comment by cklb** [comment]
Forgot to close this one. Feature is included since 0.3
