### ISSUE TITLE
installing via pip fails

### ISSUE THREAD

**Issue by cknoll** [cklb/pymoskito#64]
Operating System: Debian 9

This is the respective console dump

pip install --user pymoskito
Collecting pymoskito
  Downloading pymoskito-0.2.0.tar.gz (167kB)
    100% |████████████████████████████████| 174kB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-AtMrD9/pymoskito/setup.py", line 17, in <module>
        with open("requirements.txt") as requirements_file:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by cklb** [comment]
While other reasons may still make the installation process fail, this particular isse has ben fixed in release 0.2.1
