### ISSUE TITLE
Correct initialization of a module

### ISSUE THREAD

**Issue by TanDro** [cklb/pymoskito#73]
If an error in the init of a module happens, there is only the check
https://github.com/cklb/pymoskito/blob/044d0bdacc6f36a5cef389150d205a620ff47d06/pymoskito/simulation_interface.py#L343-L345
but the simulation starts still. Is there a currently implemented possibility to test, if the init was correct?
Background: I run cmake in the init of some new modules and it can happen, that the command fails.

**Comment by cklb** [comment]
The check you mentioned above only makes sure that all modules which are mandatory for the simulation are actually created. 
To reach this check, the '__init__' calls of all selected routines must not raise any exception. 
If such an exception is raised, the whole application crashes immediately, which can indeed be done better.
Do you want to test the correct behaviour without running a simulation or which other kind of response are you expecting?

**Comment by TanDro** [comment]
Okay, it was not sure, if there is another function, that handle these behaviour. 
I do some make stuff in the init to build a library from c source. Now I have added a little exception handling of the initialization of a module. Tank you.
